export const LOAD_PORTFOLIO_SUCCESS = 'LOAD_PORTFOLIO_SUCCESS';
export const LOAD_PORTFOLIO_FAILED = 'LOAD_PORTFOLIO_FAILED';
export const UPDATE_STOCK_PRICE_SUCCESS = 'UPDATE_STOCK_PRICE_SUCCESS';
export const UPDATE_STOCK_PRICE_FAILED = 'UPDATE_STOCK_PRICE_FAILED';
export const REBALANCE_PORTFOLIO_SUCCESS = 'REBALANCE_PORTFOLIO_SUCCESS';
export const REBALANCE_PORTFOLIO_FAILED = 'REBALANCE_PORTFOLIO_FAILED';
